CREATE TABLE FACILITIES (
	ID CHAR(16) FOR BIT DATA NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_AT TIMESTAMP NOT NULL,
	CUST_ID VARCHAR(20) NOT NULL,
	UICI VARCHAR(20) NOT NULL,
	CONSTRAINT FACILITIES_PK PRIMARY KEY (ID)
);
