CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE FACILITIES (
	ID CHAR(16) FOR BIT DATA NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_AT TIMESTAMP NOT NULL,
	CUST_ID VARCHAR(20) NOT NULL,
	UICI VARCHAR(20) NOT NULL,
	FAC_UID VARCHAR(255) NOT NULL,
	FAC_URI VARCHAR(255) NOT NULL,
	FAC_KEY VARCHAR(255) FOR BIT DATA NOT NULL,
	CONSTRAINT FACILITIES_PK PRIMARY KEY (ID)
);

CREATE TABLE FACILITY_REGS (
	ID BIGINT NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_AT TIMESTAMP NOT NULL,
	CUST_ID VARCHAR(20) NOT NULL,
	UICI VARCHAR(20) NOT NULL,
	FAC_UID VARCHAR(255) NOT NULL,
	FAC_URI VARCHAR(255) NOT NULL,
	FAC_KEY VARCHAR(255) FOR BIT DATA NOT NULL,
	FAC_NONCE VARCHAR(24) FOR BIT DATA NOT NULL,
	EXCH_NONCE VARCHAR(24) FOR BIT DATA NOT NULL,
	CONSTRAINT FACILITY_REGS_PK PRIMARY KEY (ID)
);
