logging:
  level:
    ROOT: INFO
  pattern:
    console: "${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file:  "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: db/migration/{vendor}

grpc:
  server:
    port: 9091
    address: "0.0.0.0"

server:
  port: 8081

spring:
  datasource:
    tomcat:
      initialSize: 1
      maxActive: 10
      minIdle: 1
      maxIdle: 2
      testOnBorrow: true
      testWhileIdle: true
      validationQuery: VALUES CURRENT_DATE
      timeBetweenEvictionRunsMillis: 35000
      minEvictableIdleTimeMillis: 55000
      validationInterval: 35000
      removeAbandoned: true
      removeAbandonedTimeout: 600
      jdbcInterceptors: "ConnectionState;StatementCache(prepared=true,callable=false,max=50);ResetAbandonedTimer"
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.DerbyTenSevenDialect
        jdbc.time_zone: UTC

ssh:
  shell:
    prompt:
      color: green
      text: 'Xchg> '
      
xchg:
  uid: monopoly-utility
  facility:
    conn:
      usePlaintext: true

---
debugMode: true

logging:
  level:
    org.springframework.boot.autoconfigure: INFO

spring:
  profiles: development
  datasource:
    url: jdbc:derby:esi-exchange;create=true
    username: esi
    password: esi
    platform: derby
    initialize: true
  mvc:
    async.request-timeout: -1

ssh:
  shell:
    enabled: true
